"""Canonical identity, infrastructure & content entities — DATABASE.md §3–§7.

These tables complete the canonical schema (``docs/schemas/postgres_schema.sql``)
alongside the prototype's ``actors``/``personas``/``identifiers`` (identity.py).
They are populated from Phase 3 (ingestion) onward; the models exist from day
one so migrations and the ingestion boundary match DATABASE.md exactly.

Conventions (DATABASE.md §1):
- UUID PKs generated by the app.
- ``normalized_key`` is the canonical dedup key, globally unique per table.
- ``metadata`` JSONB flexible fields; TIMESTAMPTZ-equivalent naive-UTC here.
- No hard deletes for intelligence data: ``status`` soft-delete columns.

Column semantics stay engine-agnostic: GUID → UUID on PostgreSQL / CHAR(36) on
SQLite; JSONBVariant → JSONB / JSON. The same models serve both modes.
"""
from __future__ import annotations

from datetime import datetime
from typing import Any, Optional

from sqlalchemy import (
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Interval,
    Numeric,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from .base import Base, GUID, IDMixin, JSONBVariant, SeenMixin, StampMixin

# Controlled vocabularies (mirror docs/schemas/postgres_schema.sql CHECKs)
SOURCE_KINDS = ("marketplace", "forum", "certificate_archive", "dns_archive",
                "blockchain_indexer", "paste")
ACCESS_METHODS = ("synthetic", "authorized", "public")
HANDLE_CATEGORIES = ("marketplace", "forum", "paste", "other")
WALLET_CHAINS = ("btc", "xmr", "eth")
INFRA_KINDS = ("ip", "asn", "server", "shared_host", "netblock")
DOMAIN_STATUSES = ("active", "parked", "expired")
PLATFORM_STATUSES = ("operating", "seized", "offline")
PLATFORM_TYPES = ("marketplace", "forum")
OBSERVATION_KINDS = (
    "handle_seen", "pgp_seen", "wallet_transfer", "post_created", "cert_observed",
    "dns_observed", "domain_registered", "infra_seen", "persona_migration", "custom",
)


# ---------------------------------------------------------------------------
# §3 Core identity entities
# ---------------------------------------------------------------------------

class Handle(Base, IDMixin, SeenMixin, StampMixin):
    """A platform handle as observed on a source. Deduped on normalized_key."""

    __tablename__ = "handles"

    source_id: Mapped[str] = mapped_column(
        ForeignKey("sources.id", ondelete="RESTRICT"), nullable=False
    )
    value: Mapped[str] = mapped_column(Text, nullable=False)
    normalized: Mapped[str] = mapped_column(Text, nullable=False)
    normalized_key: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    # Resolved at ingest to forums.id or marketplaces.id — polymorphic, so no
    # single FK (smallest consistent reading of DATABASE.md §3 handles).
    platform_id: Mapped[Optional[str]] = mapped_column(GUID())
    platform_type: Mapped[Optional[str]] = mapped_column(String(20))
    category: Mapped[str] = mapped_column(
        String(20), nullable=False, default="other"
    )
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="active")

    source: Mapped["Source"] = relationship(lazy="joined")  # type: ignore[name-defined]  # noqa: F821

    __table_args__ = (
        CheckConstraint(
            "platform_type IN ('marketplace', 'forum') OR platform_type IS NULL",
            name="ck_handles_platform_type",
        ),
        CheckConstraint(
            "category IN ('marketplace', 'forum', 'paste', 'other')",
            name="ck_handles_category",
        ),
        CheckConstraint("status IN ('active', 'inactive')", name="ck_handles_status"),
        Index("idx_handles_platform", "platform_id"),
    )


class Alias(Base, IDMixin, SeenMixin, StampMixin):
    """An identity label (persona name, nickname) — DATABASE.md §3."""

    __tablename__ = "aliases"

    source_id: Mapped[str] = mapped_column(
        ForeignKey("sources.id", ondelete="RESTRICT"), nullable=False
    )
    value: Mapped[str] = mapped_column(Text, nullable=False)
    normalized: Mapped[str] = mapped_column(Text, nullable=False)
    normalized_key: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    kind: Mapped[str] = mapped_column(String(40), nullable=False, default="nickname")


class PGPKey(Base, IDMixin, SeenMixin, StampMixin):
    """A PGP fingerprint sighting. Deduped on uppercase fingerprint."""

    __tablename__ = "pgp_keys"

    source_id: Mapped[str] = mapped_column(
        ForeignKey("sources.id", ondelete="RESTRICT"), nullable=False
    )
    fingerprint: Mapped[str] = mapped_column(String(64), nullable=False)
    normalized_key: Mapped[str] = mapped_column(String(64), nullable=False, unique=True)
    key_id: Mapped[Optional[str]] = mapped_column(String(32))
    user_id: Mapped[Optional[str]] = mapped_column(Text)
    algorithm: Mapped[Optional[str]] = mapped_column(String(40))


class Wallet(Base, IDMixin, SeenMixin, StampMixin):
    """A blockchain wallet identifier (synthetic chains only) — DATABASE.md §3."""

    __tablename__ = "wallets"

    source_id: Mapped[str] = mapped_column(
        ForeignKey("sources.id", ondelete="RESTRICT"), nullable=False
    )
    address: Mapped[str] = mapped_column(Text, nullable=False)
    normalized_key: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    chain: Mapped[str] = mapped_column(String(10), nullable=False)
    address_type: Mapped[Optional[str]] = mapped_column(String(40))

    __table_args__ = (
        CheckConstraint("chain IN ('btc', 'xmr', 'eth')", name="ck_wallets_chain"),
    )


# ---------------------------------------------------------------------------
# §4 Infrastructure entities
# ---------------------------------------------------------------------------

class Domain(Base, IDMixin, SeenMixin, StampMixin):
    """A domain record (punycode, trailing dot stripped) — DATABASE.md §4."""

    __tablename__ = "domains"

    source_id: Mapped[str] = mapped_column(
        ForeignKey("sources.id", ondelete="RESTRICT"), nullable=False
    )
    name: Mapped[str] = mapped_column(Text, nullable=False)
    normalized_key: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    registrar: Mapped[Optional[str]] = mapped_column(Text)
    registration_date: Mapped[Optional[datetime]] = mapped_column(DateTime)
    expiration_date: Mapped[Optional[datetime]] = mapped_column(DateTime)
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="active")

    __table_args__ = (
        CheckConstraint("status IN ('active', 'parked', 'expired')", name="ck_domains_status"),
    )


class Infrastructure(Base, IDMixin, SeenMixin, StampMixin):
    """Hosting/ASN-level infrastructure (synthetic TEST-NET only) — DATABASE.md §4."""

    __tablename__ = "infrastructure"

    source_id: Mapped[str] = mapped_column(
        ForeignKey("sources.id", ondelete="RESTRICT"), nullable=False
    )
    kind: Mapped[str] = mapped_column(String(20), nullable=False)
    value: Mapped[str] = mapped_column(Text, nullable=False)
    normalized_key: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    organization: Mapped[Optional[str]] = mapped_column(Text)
    country: Mapped[Optional[str]] = mapped_column(String(2))

    __table_args__ = (
        CheckConstraint(
            "kind IN ('ip', 'asn', 'server', 'shared_host', 'netblock')",
            name="ck_infrastructure_kind",
        ),
    )


class CertificateMetadata(Base, IDMixin, SeenMixin, StampMixin):
    """TLS certificate metadata (CN/SAN/issuer/serial) — DATABASE.md §4."""

    __tablename__ = "certificate_metadata"

    source_id: Mapped[str] = mapped_column(
        ForeignKey("sources.id", ondelete="RESTRICT"), nullable=False
    )
    serial: Mapped[str] = mapped_column(Text, nullable=False)
    normalized_key: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    cn: Mapped[Optional[str]] = mapped_column(Text)
    san: Mapped[list[Any]] = mapped_column(JSONBVariant, nullable=False, default=list)
    issuer: Mapped[Optional[str]] = mapped_column(Text)
    not_before: Mapped[Optional[datetime]] = mapped_column(DateTime)
    not_after: Mapped[Optional[datetime]] = mapped_column(DateTime)
    fingerprint_sha256: Mapped[Optional[str]] = mapped_column(String(64))


# ---------------------------------------------------------------------------
# §5 Platforms & content
# ---------------------------------------------------------------------------

class Marketplace(Base, IDMixin, StampMixin):
    """A synthetic marketplace platform — DATABASE.md §5."""

    __tablename__ = "marketplaces"

    name: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    codename: Mapped[Optional[str]] = mapped_column(String(80))
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="operating")
    domain_id: Mapped[Optional[str]] = mapped_column(
        ForeignKey("domains.id"), nullable=True
    )
    description: Mapped[Optional[str]] = mapped_column(Text)
    metadata_json: Mapped[dict[str, Any]] = mapped_column(
        "metadata", JSONBVariant, nullable=False, default=dict
    )

    __table_args__ = (
        CheckConstraint(
            "status IN ('operating', 'seized', 'offline')", name="ck_marketplaces_status"
        ),
    )


class Forum(Base, IDMixin, StampMixin):
    """A synthetic forum platform — DATABASE.md §5."""

    __tablename__ = "forums"

    name: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    codename: Mapped[Optional[str]] = mapped_column(String(80))
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="operating")
    category: Mapped[Optional[str]] = mapped_column(String(60))
    domain_id: Mapped[Optional[str]] = mapped_column(
        ForeignKey("domains.id"), nullable=True
    )

    __table_args__ = (
        CheckConstraint(
            "status IN ('operating', 'seized', 'offline')", name="ck_forums_status"
        ),
    )


class Post(Base, IDMixin, SeenMixin, StampMixin):
    """A forum/marketplace post (feeds stylometry) — DATABASE.md §5."""

    __tablename__ = "posts"

    external_id: Mapped[str] = mapped_column(Text, nullable=False)
    # forums.id or marketplaces.id — polymorphic per DDL, no single FK.
    platform_id: Mapped[str] = mapped_column(GUID(), nullable=False)
    platform_type: Mapped[str] = mapped_column(String(20), nullable=False)
    author_handle_id: Mapped[Optional[str]] = mapped_column(
        ForeignKey("handles.id", ondelete="SET NULL")
    )
    author_raw: Mapped[Optional[str]] = mapped_column(Text)
    title: Mapped[Optional[str]] = mapped_column(Text)
    body: Mapped[Optional[str]] = mapped_column(Text)
    posted_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    language: Mapped[str] = mapped_column(String(10), nullable=False, default="en")
    site: Mapped[Optional[str]] = mapped_column(Text)
    source_id: Mapped[str] = mapped_column(
        ForeignKey("sources.id", ondelete="RESTRICT"), nullable=False
    )
    metadata_json: Mapped[dict[str, Any]] = mapped_column(
        "metadata", JSONBVariant, nullable=False, default=dict
    )

    author_handle: Mapped[Optional["Handle"]] = relationship()

    __table_args__ = (
        CheckConstraint(
            "platform_type IN ('marketplace', 'forum')", name="ck_posts_platform_type"
        ),
        UniqueConstraint("source_id", "platform_id", "external_id", name="uq_posts_external"),
        Index("idx_posts_handle", "author_handle_id"),
        Index("idx_posts_posted", "posted_at"),
    )


# ---------------------------------------------------------------------------
# §6 Observations & the relationship↔observation join
# ---------------------------------------------------------------------------

class Observation(Base, IDMixin, SeenMixin, StampMixin):
    """A normalized raw fact — the atomic unit of the intelligence record."""

    __tablename__ = "observations"

    source_id: Mapped[str] = mapped_column(
        ForeignKey("sources.id", ondelete="RESTRICT"), nullable=False
    )
    kind: Mapped[str] = mapped_column(String(40), nullable=False)
    subject_type: Mapped[str] = mapped_column(String(40), nullable=False)
    subject_id: Mapped[str] = mapped_column(GUID(), nullable=False)
    occurred_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    details: Mapped[dict[str, Any]] = mapped_column(JSONBVariant, nullable=False, default=dict)
    raw: Mapped[Optional[str]] = mapped_column(Text)

    __table_args__ = (
        UniqueConstraint(
            "source_id", "kind", "subject_id", "occurred_at", name="uq_observation"
        ),
        Index("idx_observations_subject", "subject_type", "subject_id"),
        Index("idx_observations_occurred", "occurred_at"),
    )


class RelationshipObservation(Base):
    """Provenance join: which observations back an inferred relationship."""

    __tablename__ = "relationship_observations"

    relationship_id: Mapped[str] = mapped_column(
        ForeignKey("relationships.id", ondelete="CASCADE"), primary_key=True
    )
    observation_id: Mapped[str] = mapped_column(
        ForeignKey("observations.id", ondelete="CASCADE"), primary_key=True
    )


# ---------------------------------------------------------------------------
# §8 Profiles (behavior & stylometry)
# ---------------------------------------------------------------------------

class BehaviorProfile(Base, IDMixin, StampMixin):
    """Posting-behavior profile per actor/handle — DATABASE.md §8."""

    __tablename__ = "behavior_profiles"

    actor_id: Mapped[str] = mapped_column(
        ForeignKey("actors.id", ondelete="CASCADE"), nullable=False
    )
    handle_id: Mapped[Optional[str]] = mapped_column(
        ForeignKey("handles.id", ondelete="SET NULL")
    )
    frequency_mean: Mapped[Optional[float]] = mapped_column(Numeric(10, 4))
    interval_mean: Mapped[Optional[Any]] = mapped_column(Interval)
    # Numeric[] in the DDL; JSON arrays keep SQLite parity (flagged drift).
    hour_histogram: Mapped[list[Any]] = mapped_column(JSONBVariant, nullable=False, default=list)
    weekday_histogram: Mapped[list[Any]] = mapped_column(JSONBVariant, nullable=False, default=list)
    lifecycle: Mapped[dict[str, Any]] = mapped_column(JSONBVariant, nullable=False, default=dict)
    migrations: Mapped[list[Any]] = mapped_column(JSONBVariant, nullable=False, default=list)
    raw_vector: Mapped[dict[str, Any]] = mapped_column(JSONBVariant, nullable=False, default=dict)
    source_id: Mapped[Optional[str]] = mapped_column(ForeignKey("sources.id"))
    computed_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime, server_default=func.now()
    )
    metadata_json: Mapped[dict[str, Any]] = mapped_column(
        "metadata", JSONBVariant, nullable=False, default=dict
    )

    __table_args__ = (Index("idx_behavior_actor", "actor_id"),)


class StylometricProfile(Base, IDMixin, StampMixin):
    """Writing-style profile per actor/handle — DATABASE.md §8."""

    __tablename__ = "stylometric_profiles"

    actor_id: Mapped[str] = mapped_column(
        ForeignKey("actors.id", ondelete="CASCADE"), nullable=False
    )
    handle_id: Mapped[Optional[str]] = mapped_column(
        ForeignKey("handles.id", ondelete="SET NULL")
    )
    corpus_size: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    avg_sentence_len: Mapped[Optional[float]] = mapped_column(Numeric(8, 3))
    ttr: Mapped[Optional[float]] = mapped_column(Numeric(8, 5))
    char_ngram_vector: Mapped[dict[str, Any]] = mapped_column(JSONBVariant, nullable=False, default=dict)
    word_ngram_vector: Mapped[dict[str, Any]] = mapped_column(JSONBVariant, nullable=False, default=dict)
    function_word_rates: Mapped[dict[str, Any]] = mapped_column(JSONBVariant, nullable=False, default=dict)
    punctuation_rates: Mapped[dict[str, Any]] = mapped_column(JSONBVariant, nullable=False, default=dict)
    repeated_phrases: Mapped[list[Any]] = mapped_column(JSONBVariant, nullable=False, default=list)
    top_features: Mapped[list[Any]] = mapped_column(JSONBVariant, nullable=False, default=list)
    source_id: Mapped[Optional[str]] = mapped_column(ForeignKey("sources.id"))
    computed_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime, server_default=func.now()
    )
    metadata_json: Mapped[dict[str, Any]] = mapped_column(
        "metadata", JSONBVariant, nullable=False, default=dict
    )

    __table_args__ = (Index("idx_stylo_actor", "actor_id"),)
