"""phase 2 initial schema

Revision ID: 1569534a6fe4
Revises: 
Create Date: 2026-09-27 00:12:37.840996

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

import app.models.base  # noqa: E402  — TypeDecorator reprs resolve via the module



# revision identifiers, used by Alembic.
revision = '1569534a6fe4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysts',
    sa.Column('username', app.models.base.CITEXT(), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('email', app.models.base.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('analyst_id', app.models.base.GUID(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource_type', sa.String(length=40), nullable=True),
    sa.Column('resource_id', app.models.base.GUID(), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=200), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_analyst', 'audit_events', ['analyst_id'], unique=False)
    op.create_index('ix_audit_occurred', 'audit_events', ['occurred_at'], unique=False)
    op.create_index('ix_audit_resource', 'audit_events', ['resource_type', 'resource_id'], unique=False)
    op.create_table('graph_sync_state',
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', app.models.base.GUID(), nullable=False),
    sa.Column('sync_status', sa.String(length=10), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("sync_status IN ('pending', 'synced', 'failed')", name='ck_graph_sync_state_status'),
    sa.PrimaryKeyConstraint('entity_type', 'entity_id')
    )
    op.create_table('scan_jobs',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('sources_processed', sa.Integer(), nullable=False),
    sa.Column('new_artifacts', sa.Integer(), nullable=False),
    sa.Column('new_identifiers', sa.Integer(), nullable=False),
    sa.Column('new_relationships', sa.Integer(), nullable=False),
    sa.Column('high_confidence_relationships', sa.Integer(), nullable=False),
    sa.Column('errors', app.models.base.JSONBVariant(), nullable=False),
    sa.Column('batch_id', app.models.base.GUID(), nullable=True),
    sa.Column('trigger', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.CheckConstraint("kind IN ('autonomous', 'demo_run', 'manual')", name='ck_scan_jobs_kind'),
    sa.CheckConstraint("status IN ('queued', 'running', 'completed', 'failed')", name='ck_scan_jobs_status'),
    sa.CheckConstraint("trigger IN ('beat', 'api', 'demo')", name='ck_scan_jobs_trigger'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('idx_scan_jobs_status', 'scan_jobs', ['status', 'created_at'], unique=False)
    op.create_table('sources',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('access_method', sa.String(length=40), nullable=False),
    sa.Column('trust_level', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('last_scanned_at', sa.DateTime(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("access_method IN ('synthetic', 'authorized', 'public')", name='ck_sources_access_method'),
    sa.CheckConstraint('trust_level BETWEEN 0 AND 100', name='ck_sources_trust_level'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('actors',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('attribution_confidence', sa.Float(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('merged_into_id', app.models.base.GUID(), nullable=True),
    sa.Column('created_by', app.models.base.GUID(), nullable=True),
    sa.Column('source_id', app.models.base.GUID(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('last_scan_at', sa.DateTime(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['merged_into_id'], ['actors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('idx_actors_status', 'actors', ['status'], unique=False)
    op.create_index('ix_actors_last_scan', 'actors', ['last_scan_at'], unique=False)
    op.create_index('ix_actors_risk_category', 'actors', ['risk_level', 'category'], unique=False)
    op.create_table('aliases',
    sa.Column('source_id', app.models.base.GUID(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('normalized', sa.Text(), nullable=False),
    sa.Column('normalized_key', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_key')
    )
    op.create_table('certificate_metadata',
    sa.Column('source_id', app.models.base.GUID(), nullable=False),
    sa.Column('serial', sa.Text(), nullable=False),
    sa.Column('normalized_key', sa.Text(), nullable=False),
    sa.Column('cn', sa.Text(), nullable=True),
    sa.Column('san', app.models.base.JSONBVariant(), nullable=False),
    sa.Column('issuer', sa.Text(), nullable=True),
    sa.Column('not_before', sa.DateTime(), nullable=True),
    sa.Column('not_after', sa.DateTime(), nullable=True),
    sa.Column('fingerprint_sha256', sa.String(length=64), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_key')
    )
    op.create_table('domains',
    sa.Column('source_id', app.models.base.GUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('normalized_key', sa.Text(), nullable=False),
    sa.Column('registrar', sa.Text(), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'parked', 'expired')", name='ck_domains_status'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_key')
    )
    op.create_table('handles',
    sa.Column('source_id', app.models.base.GUID(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('normalized', sa.Text(), nullable=False),
    sa.Column('normalized_key', sa.Text(), nullable=False),
    sa.Column('platform_id', app.models.base.GUID(), nullable=True),
    sa.Column('platform_type', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("category IN ('marketplace', 'forum', 'paste', 'other')", name='ck_handles_category'),
    sa.CheckConstraint("platform_type IN ('marketplace', 'forum') OR platform_type IS NULL", name='ck_handles_platform_type'),
    sa.CheckConstraint("status IN ('active', 'inactive')", name='ck_handles_status'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_key')
    )
    op.create_index('idx_handles_platform', 'handles', ['platform_id'], unique=False)
    op.create_table('infrastructure',
    sa.Column('source_id', app.models.base.GUID(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('normalized_key', sa.Text(), nullable=False),
    sa.Column('organization', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("kind IN ('ip', 'asn', 'server', 'shared_host', 'netblock')", name='ck_infrastructure_kind'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_key')
    )
    op.create_table('investigations',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('lead_analyst_id', app.models.base.GUID(), nullable=False),
    sa.Column('participants', app.models.base.JSONBVariant(), nullable=False),
    sa.Column('targets', sa.JSON(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lead_analyst_id'], ['analysts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_investigations_status', 'investigations', ['status'], unique=False)
    op.create_table('observations',
    sa.Column('source_id', app.models.base.GUID(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('subject_type', sa.String(length=40), nullable=False),
    sa.Column('subject_id', app.models.base.GUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('details', app.models.base.JSONBVariant(), nullable=False),
    sa.Column('raw', sa.Text(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'kind', 'subject_id', 'occurred_at', name='uq_observation')
    )
    op.create_index('idx_observations_occurred', 'observations', ['occurred_at'], unique=False)
    op.create_index('idx_observations_subject', 'observations', ['subject_type', 'subject_id'], unique=False)
    op.create_table('pgp_keys',
    sa.Column('source_id', app.models.base.GUID(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('normalized_key', sa.String(length=64), nullable=False),
    sa.Column('key_id', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.Column('algorithm', sa.String(length=40), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_key')
    )
    op.create_table('relationships',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('from_type', sa.String(length=40), nullable=False),
    sa.Column('from_id', app.models.base.GUID(), nullable=False),
    sa.Column('to_type', sa.String(length=40), nullable=False),
    sa.Column('to_id', app.models.base.GUID(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('band', sa.String(length=20), nullable=False),
    sa.Column('scoring_factors', app.models.base.JSONBVariant(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('hypothesis_label', sa.String(length=200), nullable=True),
    sa.Column('evidence_ids', app.models.base.JSONBVariant(), nullable=False),
    sa.Column('ruled_out_summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', app.models.base.GUID(), nullable=True),
    sa.Column('reviewed_by', app.models.base.GUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('source_id', app.models.base.GUID(), nullable=True),
    sa.Column('engine_ref', sa.String(length=60), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_rel_from', 'relationships', ['from_type', 'from_id'], unique=False)
    op.create_index('ix_rel_kind', 'relationships', ['kind'], unique=False)
    op.create_index('ix_rel_status_confidence', 'relationships', ['status', 'confidence'], unique=False)
    op.create_index('ix_rel_to', 'relationships', ['to_type', 'to_id'], unique=False)
    op.create_table('wallets',
    sa.Column('source_id', app.models.base.GUID(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('normalized_key', sa.Text(), nullable=False),
    sa.Column('chain', sa.String(length=10), nullable=False),
    sa.Column('address_type', sa.String(length=40), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("chain IN ('btc', 'xmr', 'eth')", name='ck_wallets_chain'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_key')
    )
    op.create_table('alerts',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('actor_id', app.models.base.GUID(), nullable=True),
    sa.Column('relationship_id', app.models.base.GUID(), nullable=True),
    sa.Column('source_id', app.models.base.GUID(), nullable=True),
    sa.Column('acknowledged_by', app.models.base.GUID(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.CheckConstraint("kind IN ('new_high_confidence', 'new_handle_seen', 'persona_migration', 'new_evidence', 'system')", name='ck_alerts_kind'),
    sa.CheckConstraint("severity IN ('info', 'low', 'medium', 'high')", name='ck_alerts_severity'),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ),
    sa.ForeignKeyConstraint(['relationship_id'], ['relationships.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('idx_alerts_created', 'alerts', ['created_at'], unique=False)
    op.create_table('behavior_profiles',
    sa.Column('actor_id', app.models.base.GUID(), nullable=False),
    sa.Column('handle_id', app.models.base.GUID(), nullable=True),
    sa.Column('frequency_mean', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('interval_mean', sa.Interval(), nullable=True),
    sa.Column('hour_histogram', app.models.base.JSONBVariant(), nullable=False),
    sa.Column('weekday_histogram', app.models.base.JSONBVariant(), nullable=False),
    sa.Column('lifecycle', app.models.base.JSONBVariant(), nullable=False),
    sa.Column('migrations', app.models.base.JSONBVariant(), nullable=False),
    sa.Column('raw_vector', app.models.base.JSONBVariant(), nullable=False),
    sa.Column('source_id', app.models.base.GUID(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('metadata', app.models.base.JSONBVariant(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['handle_id'], ['handles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_behavior_actor', 'behavior_profiles', ['actor_id'], unique=False)
    op.create_table('evidence',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('strength', sa.String(length=20), nullable=False),
    sa.Column('class', sa.String(length=30), nullable=False),
    sa.Column('score_contribution', sa.Float(), nullable=False),
    sa.Column('source_id', app.models.base.GUID(), nullable=True),
    sa.Column('relationship_id', app.models.base.GUID(), nullable=True),
    sa.Column('observation_ids', app.models.base.JSONBVariant(), nullable=False),
    sa.Column('details', app.models.base.JSONBVariant(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['relationship_id'], ['relationships.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_evidence_kind', 'evidence', ['kind'], unique=False)
    op.create_index('ix_evidence_relationship', 'evidence', ['relationship_id'], unique=False)
    op.create_table('forums',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('codename', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('domain_id', app.models.base.GUID(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('operating', 'seized', 'offline')", name='ck_forums_status'),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('investigation_notes',
    sa.Column('investigation_id', app.models.base.GUID(), nullable=False),
    sa.Column('analyst_id', app.models.base.GUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('visibility', sa.String(length=10), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("visibility IN ('team', 'private')", name='ck_investigation_notes_visibility'),
    sa.ForeignKeyConstraint(['analyst_id'], ['analysts.id'], ),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_notes_investigation', 'investigation_notes', ['investigation_id'], unique=False)
    op.create_table('marketplaces',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('codename', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('domain_id', app.models.base.GUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', app.models.base.JSONBVariant(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('operating', 'seized', 'offline')", name='ck_marketplaces_status'),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('personas',
    sa.Column('actor_id', app.models.base.GUID(), nullable=False),
    sa.Column('source_id', app.models.base.GUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('normalized_name', sa.String(length=120), nullable=False),
    sa.Column('platform', sa.String(length=120), nullable=False),
    sa.Column('platform_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('reputation', sa.String(length=40), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_name', 'platform', name='uq_persona_name_platform')
    )
    op.create_index('ix_personas_actor', 'personas', ['actor_id'], unique=False)
    op.create_table('posts',
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('platform_id', app.models.base.GUID(), nullable=False),
    sa.Column('platform_type', sa.String(length=20), nullable=False),
    sa.Column('author_handle_id', app.models.base.GUID(), nullable=True),
    sa.Column('author_raw', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('site', sa.Text(), nullable=True),
    sa.Column('source_id', app.models.base.GUID(), nullable=False),
    sa.Column('metadata', app.models.base.JSONBVariant(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("platform_type IN ('marketplace', 'forum')", name='ck_posts_platform_type'),
    sa.ForeignKeyConstraint(['author_handle_id'], ['handles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'platform_id', 'external_id', name='uq_posts_external')
    )
    op.create_index('idx_posts_handle', 'posts', ['author_handle_id'], unique=False)
    op.create_index('idx_posts_posted', 'posts', ['posted_at'], unique=False)
    op.create_table('relationship_observations',
    sa.Column('relationship_id', app.models.base.GUID(), nullable=False),
    sa.Column('observation_id', app.models.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relationship_id'], ['relationships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('relationship_id', 'observation_id')
    )
    op.create_table('reports',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('investigation_id', app.models.base.GUID(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=True),
    sa.Column('filters', app.models.base.JSONBVariant(), nullable=False),
    sa.Column('generated_by', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.CheckConstraint("kind IN ('pdf', 'csv', 'json')", name='ck_reports_kind'),
    sa.CheckConstraint("status IN ('queued', 'generating', 'ready', 'failed')", name='ck_reports_status'),
    sa.ForeignKeyConstraint(['generated_by'], ['analysts.id'], ),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('stylometric_profiles',
    sa.Column('actor_id', app.models.base.GUID(), nullable=False),
    sa.Column('handle_id', app.models.base.GUID(), nullable=True),
    sa.Column('corpus_size', sa.Integer(), nullable=False),
    sa.Column('avg_sentence_len', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('ttr', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('char_ngram_vector', app.models.base.JSONBVariant(), nullable=False),
    sa.Column('word_ngram_vector', app.models.base.JSONBVariant(), nullable=False),
    sa.Column('function_word_rates', app.models.base.JSONBVariant(), nullable=False),
    sa.Column('punctuation_rates', app.models.base.JSONBVariant(), nullable=False),
    sa.Column('repeated_phrases', app.models.base.JSONBVariant(), nullable=False),
    sa.Column('top_features', app.models.base.JSONBVariant(), nullable=False),
    sa.Column('source_id', app.models.base.GUID(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('metadata', app.models.base.JSONBVariant(), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['handle_id'], ['handles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stylo_actor', 'stylometric_profiles', ['actor_id'], unique=False)
    op.create_table('timeline_events',
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('actor_id', app.models.base.GUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=40), nullable=True),
    sa.Column('entity_id', app.models.base.GUID(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('confidence_delta', sa.Float(), nullable=True),
    sa.Column('source_id', app.models.base.GUID(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_timeline_actor', 'timeline_events', ['actor_id', 'occurred_at'], unique=False)
    op.create_index('ix_timeline_occurred', 'timeline_events', ['occurred_at'], unique=False)
    op.create_table('identifiers',
    sa.Column('actor_id', app.models.base.GUID(), nullable=False),
    sa.Column('persona_id', app.models.base.GUID(), nullable=True),
    sa.Column('source_id', app.models.base.GUID(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('value', sa.String(length=400), nullable=False),
    sa.Column('normalized_value', sa.String(length=400), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('id', app.models.base.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('persona_id', 'kind', 'normalized_value', name='uq_identifier_scope')
    )
    op.create_index('ix_identifiers_actor', 'identifiers', ['actor_id'], unique=False)
    op.create_index('ix_identifiers_kind_value', 'identifiers', ['kind', 'normalized_value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_identifiers_kind_value', table_name='identifiers')
    op.drop_index('ix_identifiers_actor', table_name='identifiers')
    op.drop_table('identifiers')
    op.drop_index('ix_timeline_occurred', table_name='timeline_events')
    op.drop_index('ix_timeline_actor', table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index('idx_stylo_actor', table_name='stylometric_profiles')
    op.drop_table('stylometric_profiles')
    op.drop_table('reports')
    op.drop_table('relationship_observations')
    op.drop_index('idx_posts_posted', table_name='posts')
    op.drop_index('idx_posts_handle', table_name='posts')
    op.drop_table('posts')
    op.drop_index('ix_personas_actor', table_name='personas')
    op.drop_table('personas')
    op.drop_table('marketplaces')
    op.drop_index('idx_notes_investigation', table_name='investigation_notes')
    op.drop_table('investigation_notes')
    op.drop_table('forums')
    op.drop_index('ix_evidence_relationship', table_name='evidence')
    op.drop_index('ix_evidence_kind', table_name='evidence')
    op.drop_table('evidence')
    op.drop_index('idx_behavior_actor', table_name='behavior_profiles')
    op.drop_table('behavior_profiles')
    op.drop_index('idx_alerts_created', table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('wallets')
    op.drop_index('ix_rel_to', table_name='relationships')
    op.drop_index('ix_rel_status_confidence', table_name='relationships')
    op.drop_index('ix_rel_kind', table_name='relationships')
    op.drop_index('ix_rel_from', table_name='relationships')
    op.drop_table('relationships')
    op.drop_table('pgp_keys')
    op.drop_index('idx_observations_subject', table_name='observations')
    op.drop_index('idx_observations_occurred', table_name='observations')
    op.drop_table('observations')
    op.drop_index('ix_investigations_status', table_name='investigations')
    op.drop_table('investigations')
    op.drop_table('infrastructure')
    op.drop_index('idx_handles_platform', table_name='handles')
    op.drop_table('handles')
    op.drop_table('domains')
    op.drop_table('certificate_metadata')
    op.drop_table('aliases')
    op.drop_index('ix_actors_risk_category', table_name='actors')
    op.drop_index('ix_actors_last_scan', table_name='actors')
    op.drop_index('idx_actors_status', table_name='actors')
    op.drop_table('actors')
    op.drop_table('sources')
    op.drop_index('idx_scan_jobs_status', table_name='scan_jobs')
    op.drop_table('scan_jobs')
    op.drop_table('graph_sync_state')
    op.drop_index('ix_audit_resource', table_name='audit_events')
    op.drop_index('ix_audit_occurred', table_name='audit_events')
    op.drop_index('ix_audit_analyst', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('analysts')
    # ### end Alembic commands ###
